# Generated by Django 5.1.4 on 2025-01-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disease_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('function', models.JSONField(default=list)),
                # ('associated_disease', models.ManyToManyField(related_name='proteins', to='disease_app.disease')),
            ],
        ),
    ]
