# Generated by Django 5.1.4 on 2025-01-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disease_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('current_disease', models.ManyToManyField(blank=True, related_name='current_patients', to='disease_app.disease')),
                ('history', models.ManyToManyField(blank=True, related_name='patient_history', to='disease_app.disease')),
            ],
        ),
    ]
