services:
  api:
    build: .
    ports: 
    - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=protein_db
    ports:
      - '5444:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # frontend:
  #   build: ./PathoMap-Frontend 
  #   ports: 
  #     - "8090:80"
  #   depends_on:
  #     api:
  #       condition: service_healthy
volumes:
  postgres_data:
  